# Generated by Django 6.0 on 2026-01-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('GPU', 'Graphics Card'), ('CPU', 'Processor'), ('RAM', 'Memory'), ('SSD', 'Storage'), ('MONITOR', 'Monitor'), ('KEYBOARD', 'Keyboard'), ('MOUSE', 'Mouse'), ('HEADSET', 'Headset'), ('MOTHERBOARD', 'Motherboard'), ('CASE', 'PC Case')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
    ]
